<a href="https://colab.research.google.com/github/AlexandreMenezesSa/Python-Beginner/blob/master/Compara%C3%A7%C3%B5es_e_indexa%C3%A7%C3%A3o_booleana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Comparações e indexação booleana**

**Maior/Maior ou igual:**

In [ ]:
# importando as bibliotecas
import numpy as np

In [ ]:
# criação dos arrays
x = np.array([[1, 2], [3, 4],[11,12]])
y = np.array([1.5, 3.5])
print("x: \n", x)
print("y: \n", y)

x: 
 [[ 1  2]
 [ 3  4]
 [11 12]]
y: 
 [1.5 3.5]


In [ ]:
# comparações ponto a ponto
print("Comparação de um array com um escalar (>): \n", x > 2)  
print("Comparação de um array com um escalar (>=): \n", x >= 2)
print("Comparação de um array com um escalar (<): \n", x < 2)  
print("Comparação de um array com um escalar (<=): \n", x <= 2)
print("Comparação entre arrays (==): \n", x == x)
print("Comparação entre arrays (>): \n", x > x)
print("Comparação entre arrays (>): \n", x > y)  # broadcasting

Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [False False]
 [False False]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]
 [ True  True]]


# **Indexação booleana**

In [ ]:
x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])
print("x:\n", x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [ ]:
# indexação boolena: retornar o número de elementos
# maiores que k
k = 12
cond = x > k
print("condição: \n", cond)

print(f"elementos maiores que {k}:", x[cond])
print(f"números de elementos maiores que {k}:", len(x[cond]))

condição: 
 [[False False False]
 [False False  True]
 [ True False False]]
elementos maiores que 12: [21 42]
números de elementos maiores que 12: 2


In [ ]:
# indexação boolena: extração dos números pares
cond = x % 2 == 0  # números pares
print("condição: \n", cond)
print("números pares:", x[cond])

condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
números pares: [ 4 42  8]


In [ ]:
# indexação boolena: extração dos números ímpares
cond = x % 2 == 1  # números pares
print("condição: \n", cond)
print("números pares:", x[cond])

condição: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
números pares: [ 1  3  7 11 21  9]
