<a href="https://colab.research.google.com/github/AlexandreMenezesSa/Python-Beginner/blob/master/Fun%C3%A7%C3%B5es_Uteis_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importando as bibliotecas
import numpy as np

In [ ]:
# array
x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])
print("x:\n", x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [ ]:
# reshape: transformar a matriz em um vetor coluna
# (3, 3) vira (9, 1): 3*3 = 9*1 = 9
print("transformação de em um vetor coluna: \n", x.reshape(9, 1))

transformação de em um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [ ]:
# transposição de matriz
print("x transposta: \n", x.T)

x transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [ ]:
# np.sum: soma em um dado eixo, axis = {0: linha, 1: coluna}
print("x:\n", x)
print("média de todos elementos de x:", np.mean(x))
print("média de x ao longo das linhas:", np.mean(x, axis=1))
print("média de x ao longo das colunas:", np.mean(x, axis=0))

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
média de todos elementos de x: 11.777777777777779
média de x ao longo das linhas: [ 3.66666667 12.         19.66666667]
média de x ao longo das colunas: [15.66666667  7.33333333 12.33333333]


In [ ]:
# np.where, indentificação dos índices onde uma dada condição
# é atendida. Uso conjunto com indexação booleana
cond = x % 2 == 0  # números pares
print("condição: \n", cond)
i, j = np.where(cond) # índices x[i, j] = x[cond]
print("índice i (linhas):", i)
print("índice j (colunas):", j) 

condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
índice i (linhas): [1 2 2]
índice j (colunas): [0 0 1]


In [ ]:
# indexação booleana e slicing: selecionar as linhas
# de x que possuem algum número par
print("x:\n", x)
cond = x % 2 == 0  # números pares
print("condição: \n", cond)

# # se houver alguma condição True na linha, a soma será > 0
i_row = np.where(np.sum(cond, axis=1))[0]
print("índice das linhas que possuem números pares:", i_row)
print("linhas que possuem número pares: \n", x[i_row, :])  


x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
índice das linhas que possuem números pares: [1 2]
linhas que possuem número pares: 
 [[ 4 11 21]
 [42  8  9]]
